python main.py --mode=train \
		--exp_name=arggen_mt_trans_100k \
	        --encode_passage \
		--type_conditional_lm \
		--task=arggen \
		--batch_size=48 \
		--num_train_epochs=100 \
		--logging_freq=2 \
    	--max_src_words=500 \
	    --max_passage_words=200 \
		--max_sent_num=10 \
		--max_bank_size=70 
