python main.py --mode=predict \
    --exp_name=arggen_mt_20_noEncMulti \
    --encode_passage \
    --replace_unk \
    --type_conditional_lm \
    --infer_fold=4 \
    --infer_fold_selected=4 \
    --max_tgt_words=150 \
    --task=arggen \
    --batch_size=32 \
    --load_model_path=epoch_22_train_167.7611_val_182.6174_ppl_7.3670.tar
